import Head from 'next/head'
import styles from '../styles/Home.module.css'
import assignTLE from './assignTLE'
import Sidebar from '../components/sidebar'
import Layout from '../components/layout'
import React, { useState, useEffect } from 'react';
import { getLatLngObj } from "tle.js";
import InfoBoxPrint from '../components/infoBoxPrint'


const tle = `ISS (ZARYA)
1 25544U 98067A   22200.18518544  .00008537  00000+0  15726-3 0  9998
2 25544  51.6408 178.1024 0004971  26.6345  84.2777 15.50023189 350148`; 



export default function Map3D(){
  const [dark,setDark] = useState(true);
  const [sidebarOpen,setSidebarOpen] = useState(false);
  const [ID,setID] = useState(25544);
  function assignTheme(dark){
    {if(dark){
      if(sidebarOpen){
      return (styles.mainDark)}
      else {return (styles.mainDarkClose)}}
      else{
        if(sidebarOpen){
          return (styles.main)}
          else {return (styles.mainClose)}
      }
  }}
  
  return(
    <> 
  <div style={{ height: '100vh' , width: '100%'}}>
     <Head>
        <title>Satellite Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar setDark={setDark} setSidebarOpen={setSidebarOpen}/>
      <main className={assignTheme(dark,sidebarOpen)}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> 
        <h2>{assignTLE(ID)}</h2>
        <h2>{getLatLngObj(tle,Date.now()).lat}</h2>
        <h2>{tle}</h2>
        <h2>'hola'</h2>
        <h2>is dark? {dark?('YES'):('no')}</h2>
        <h2>is open? {sidebarOpen?('YES'):('no')}</h2>
      </main>
      </div>
      </>
  )
}